name: deploy-dev

on: pull_request

jobs:
  deploy:
    if: github.repository_owner == 'unicorn-utterances'
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # see https://dev.to/bobheadxi/branch-previews-with-google-app-engine-and-github-actions-3pco
      - name: Extract branch name
        id: get_branch
        shell: bash
        env:
          PR_HEAD: ${{ github.head_ref }}
        run: echo "##[set-output name=branch;]$(echo ${PR_HEAD#refs/heads/} | tr / -)"

      - name: Create GitHub deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ steps.get_branch.outputs.branch }}
          ref: ${{ github.head_ref }}

      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build-beta
        env:
          SITE_URL: https://${{ steps.get_branch.outputs.branch }}.unicorn-utterances.com

      - name: Pre-configure AWS profile
        run: aws configure set max_attempts 10 --profile s3-sync-action

      - uses: jakejarvis/s3-sync-action@v0.5.1
        name: Sync files to DigitalOcean Spaces
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://sfo2.digitaloceanspaces.com
          SOURCE_DIR: public
          DEST_DIR: ${{ steps.get_branch.outputs.branch }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Flush DigitalOcean Spaces cache
        run: doctl compute cdn flush ${{ secrets.DIGITALOCEAN_CDN_ID }} --files ${{ steps.get_branch.outputs.branch }}/*

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.6.2
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ steps.get_branch.outputs.branch }}.unicorn-utterances.com
